name: openttd
adopt-info: openttd
summary: OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
description: >
  OpenTTD is an open source simulation game based upon the popular
  Microprose game Transport Tycoon Deluxe, written by Chris Sawyer.
  It attempts to mimic the original game as closely as possible while
  extending it with new features.
  This is an unofficial snap containing both the engine and open* asset packs.

  * Upstream project: https://www.openttd.org/
  * Snapcraft.yaml repository: https://github.com/diddlesnaps/openttd

grade: stable
confinement: strict
base: core24

platforms:
  amd64:
  arm64:
  armhf:

apps:
  openttd:
    command: usr/games/openttd/openttd
    desktop: usr/share/applications/openttd.desktop
    extensions: [gnome]
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - network
      - network-bind

layout:
  /etc/default:
    bind: $SNAP/etc/default
  /etc/timidity:
    bind: $SNAP/etc/timidity
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/midi:
    bind: $SNAP/usr/share/midi
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds

parts:
  openttd:
    plugin: cmake
    source: https://github.com/OpenTTD/OpenTTD.git
    override-pull: |
      craftctl default
      VERSION="$(git tag --list --sort=version:refname | grep -v -E '(-RC|beta)' | tail -n1)"
      git checkout "$VERSION"
      craftctl set version="$VERSION"
      sed -E -i 's|^Icon=.*|Icon=/usr/share/icons/hicolor/256x256/apps/openttd.png|' media/openttd.desktop
    override-build: |
      craftctl default
      sed -E -i 's|SOUND_FONT=.*|SOUND_FONT=/usr/share/sounds/sf2/FluidR3_GM.sf2|' $CRAFT_PART_INSTALL/etc/default/fluidsynth
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_INSTALL_DATADIR=games
      - -DCMAKE_INSTALL_BINDIR=games/openttd
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - g++
      - patch
      - liballegro4-dev
      - libaudio-dev
      - libfluidsynth-dev
      - libfontconfig1-dev
      - libglu1-mesa-dev
      - libicu-dev
      - liblzma-dev
      - liblzo2-dev
      - libsdl2-dev
      - zlib1g-dev
    stage-packages:
      - fluid-soundfont-gm
      - fluidsynth
      - freepats
      - liballegro4.4t64
      - libaudio2
      - libfluidsynth3
      - libfontconfig1
      - libfreetype6
      - libglu1-mesa
      - libicu74
      - liblzma5
      - liblzo2-2
      - libsdl2-2.0-0
      - libsndio7.0
      - timidity

  opengfx:
    plugin: dump
    source: https://cdn.openttd.org/opengfx-releases/7.1/opengfx-7.1-all.zip
    organize:
      opengfx-*.tar: usr/games/openttd/baseset/

  opensfx:
    plugin: dump
    source: https://cdn.openttd.org/opensfx-releases/1.0.3/opensfx-1.0.3-all.zip
    organize:
      opensfx-*: usr/games/openttd/baseset/

  openmsx:
    plugin: dump
    source: https://cdn.openttd.org/openmsx-releases/0.4.2/openmsx-0.4.2-all.zip
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/games/openttd/baseset
      tar xf openmsx-* -C $SNAPCRAFT_PART_INSTALL/usr/games/openttd/baseset
